# Generated by Django 4.0 on 2022-05-31 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_productmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
